name: 'LocNess'
description: 'Generate a lines-of-code SVG and optionally publish to GitHub Pages'

inputs:
  path:
    description: 'Path to analyze'
    required: false
    default: '.'

  output:
    description: 'Output SVG file path'
    required: false
    default: 'dist/docs/loc.svg'

  publish:
    description: 'Whether to deploy the SVG to GitHub Pages'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install cloc
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y cloc jq

    - name: Run cloc and generate SVG
      shell: bash
      run: |
        mkdir -p $(dirname "${{ inputs.output }}")
        cloc ${{ inputs.path }} --json --out=cloc.json
        TOTAL=$(jq '.SUM.code' cloc.json)
        echo '<svg xmlns="http://www.w3.org/2000/svg" width="300" height="40">
          <text x="10" y="25" font-size="16">Lines of Code: '"$TOTAL"'</text>
        </svg>' > ${{ inputs.output }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SVG
        path: dist/docs/loc.svg

    - name: Deploy to GitHub Pages (optional)
      if: ${{ inputs.publish != '' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.publish }}
        publish_dir: ./dist/docs